Repository spring-projects/spring-security-kerberos, pull requests merged in 2024-05, with the labels that each got.

#187 Upgrade com.gradle.enterprise plugin to 3.16.2
  gradle.properties
Labels: type: dependency-upgrade

#184 Add Revved up by Develocity badge
  README.adoc
Labels: type: enhancement, in: docs

#156 Properly print socket address
  spring-security-kerberos-test/src/main/java/org/springframework/security/kerberos/test/MiniKdc.java
Labels: type: bug

#154 Remove unused private constructor
  spring-security-kerberos-client/src/main/java/org/springframework/security/kerberos/client/KerberosRestTemplate.java
Labels: type: task

#153 Cleanup SunJaasKerberosTicketValidator
  spring-security-kerberos-core/src/main/java/org/springframework/security/kerberos/authentication/sun/SunJaasKerberosTicketValidator.java
Labels: type: task

#125 Kerberos Login Module doesn't get the keytab configuration option if the cache is used.
  spring-security-kerberos-client/src/main/java/org/springframework/security/kerberos/client/config/SunJaasKrb5LoginConfig.java
Labels: type: bug

#110 Make SpnegoAuthenticationProcessingFilter extend OncePerRequestFilter
  spring-security-kerberos-web/src/main/java/org/springframework/security/kerberos/web/authentication/SpnegoAuthenticationProcessingFilter.java
Labels: type: bug
